server:
  port: 8761

spring:
  application:
    name: sim-eureka

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false  #默认true，单机环境设置为false，表示不向注册中心注册自己
    fetch-registry: false     #默认true，单机环境设置为false，表示不需要向注册中心检索自己
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/